initial PR
hpcugent/openstack-auto-scaling pull request #1
Opened 2023-04-19 11:30 UTC by peterhardon

adding following:
.gitignore to ignore config, lock and pid files
openstack-auto-scalingrc.example config example file
openstack-auto-scaling.sh script itself

2023-04-20 07:43 UTC, alvarosimon reviewed
@peterhardon just a few comments and suggenstions

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +  Options: -c <config_file_location> - Location of config file which is sourced by this script to provide following values
Add the option's list in a new line
```
Options:
-c
....
```

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +                                       UNDERCLOUDRC     - openstack rc file location for admin access to undercloud
Remove unnecessary white spaces, in this case probably just 4 white spaces to ident, if not it is quite difficult to read from a terminal.
Try to keep the line's length below 79 characters  if possible.

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +  Cron entry example: */10 * * * * $SCRIPT_NAME -c /home/stack/openstack-auto-scaling/openstack-auto-scalingrc >/dev/null
Not related with the script itself.
It should be included into the README.md file not here.

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +  Script to run prior overcloud upgrade/change example: touch $LOCKFILE
Idem, should go to README.me file.
Probably we should use flock running the script not touch.

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +while getopts ":tc:u:l" options; do
Add `--help` `-h` options here

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +PID="$(cat $PIDFILE)" && ps -p "$PID" &>/dev/null && grep "$SCRIPT_NAME" </proc/"$PID"/cmdline &>/dev/null && \
You do not need this if you use flock, just check the lock file is there

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +    c)
also add longnames options like `--config`

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +[ "$CONFIG" == "" ] && log "1" "Missing mandatory -c argument." 1>&2 && exit_abnormal
maybe we should include this also as optional, the script should look for a default location like `/home/stack/openstack-auto-scaling.conf`  first or similar

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +[ "$LOCKFILE_OVERRIDE" != "" ] && LOCKFILE="$LOCKFILE_OVERRIDE"
Move all these lines to parse the conf file into a function like `parse_configuration`

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +    agg_group_hypervisor_list="$(openstack_overcloud aggregate show "$agg_group" -f json -c hosts |jq --raw-output '.hosts[]')"
if you use bash probably its better if you do not use json and its also easier to parse, just getting the hosts list with  `-f shell`

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +    #COMPUTES SHUTDOWN
Move this to a function to poweroff computes

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +        log "2" "Script in TEST MODE. No action is taken on hypervisors."
Change this to info log not error

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +        log "0" "Enabling nova-compute service for hypervisors: $(echo $computes_hostnames_to_disable) now.."
`Disabling nova-compute..`

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +    #COMPUTES STARTUP
Move this to a new function to startup nodes

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +      if [ "$TESTMODE" == "false" ]; then
You are copy-pasting the same code, you can just move this into a new generic function and give it the list of nodes to poweroff/poweron.

2023-04-20 07:43 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +        log "2" "Script in TEST MODE. No action is taken on hypervisors."
Use info instead  of error

2023-04-20 13:11 UTC, peterhardon commented on openstack-auto-scaling.sh
> +        log "2" "Script in TEST MODE. No action is taken on hypervisors."
"2" means warning

2023-04-20 13:12 UTC, peterhardon commented on openstack-auto-scaling.sh
> +        log "2" "Script in TEST MODE. No action is taken on hypervisors."
"2" means warning

2023-04-20 13:28 UTC, wdpypere commented
did you run shellcheck on this?

2023-04-20 13:35 UTC, peterhardon commented
yes, shellchecker reports only two kind of issues
first one is sourcing the file without shellchecker comment which would be just cosmetic change for the script
second one is when using echo "text $(echo variable)" however I consider this false negative as purpose of this is to print multiple line variable as single line

2023-04-21 07:24 UTC, alvarosimon requested changes

2023-04-21 07:24 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +computes_shutdown() {
computes_shutdown and computes_startup functions are more or less the same code copy pasted, move this into a single function to poweron/poweoff as I said earlier. You only have to send to this function the list of computes and if you want to poweoff/poweon those. Also format the log strings from this function accordingly.

2023-04-21 07:24 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +computes_startup() {
this should be gone to  a single function to do both tasks to avoid copy/pasting code

2023-04-21 07:24 UTC, alvarosimon commented on openstack-auto-scaling.sh
> +                                 UNDERCLOUDRC - openstack rc file location for admin access to undercloud
do not use too many white spaces for this tab, just four should be enough

2023-04-25 14:43 UTC, alvarosimon requested changes
@peterhardon just a few comments, it looks good

2023-04-25 14:43 UTC, alvarosimon commented on openstack-auto-scaling.cron
We do not need to add a cron file in this repo or rpm, this should be done by ansible

2023-04-25 14:43 UTC, alvarosimon commented on openstack-auto-scaling.spec
> +Release: 1%{?dist}
append `ug` to the release name to make it clear its a homemade ugent package

2023-04-25 14:43 UTC, alvarosimon commented on openstack-auto-scaling.spec
> +/etc/cron.d/openstack-auto-scaling.cron
do not add/override the system's cron from the rpm, this should be done by ansible, or include the file into an ../examples directory.

2023-04-27 13:04 UTC, merged